# Use the official Node 18 Alpine image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without devDependencies
RUN npm install --legacy-peer-deps

# Copy application source code
COPY . .

# Set environment variables
ENV NODE_ENV=production
ENV PORT=88
ENV MONGO_URI=mongodb://192.168.13.84/Yuvaq_Logiyatra_testing
ENV SMTP_HOST=smtp.gmail.com
ENV SMTP_USER=techsupport@rrispat.com 
ENV SMTP_PASS=kjdgsyrnkvdmcugw
ENV CLIENT_URL=https://logiqtest.yuvaq.com
ENV SECRET=98a09ad7dasd6sfd4d5sd7fokjnu

# RRI Razorpay Test
ENV RAZORPAY_KEY_ID=rzp_test_u85r2jwM23xKlY
ENV RAZORPAY_KEY_SECRET=0q84vUiUDgL7ikOtM6q8mj8i
ENV RAZORPAY_WEBHOOK_SECRET=LogiQ_123

# MinIO configuration
ENV MINIO_ENDPOINT=192.168.13.62
ENV MINIO_PORT=9000
ENV MINIO_ACCESS_KEY=uXgiyxKRlviRvIDvolPX
ENV MINIO_SECRET_KEY=vCyBd3GQtRFtt4mSjrWS5D2mJYhjkP2tuGJzeXTi
ENV MINIO_BUCKET=tenderrr

# Subscription + Fees (ADD THESE)
ENV SUBSCRIPTION_MONTHLY_INR=499
ENV SUBSCRIPTION_YEARLY_INR=4999
ENV SUBSCRIPTION_PAY_ROLES="user,transportUser"
ENV CONFIRM_ACCEPT_FEE_PERCENT=0
ENV FINALIZE_ADVANCE_PERCENT=0

# Expose your app port
EXPOSE ${PORT}

# Run the app with node (not nodemon)
CMD ["node", "index.js"]



# docker build  --no-cache -t 192.168.13.72:5000/logiq_be_test_1_july_latest .      
# docker run -d --name logiq_be_test_1_july_latest -p 88:88 logiq_be_image

# docker tag logiq_be_image 192.168.13.72:5000/logiq_be_test_1_july_latest
# docker push 192.168.13.72:5000/logiq_be_test_1_july_latest
# docker pull 192.168.13.72:5000/logiq_be_test_1_july_latest
# docker run -d --name logiq_be_test_1_july_latest -p 88:88 192.168.13.72:5000/logiq_be_test_1_july_latest
